---
title: "Risk Factors for Mental Health"
output: 
  flexdashboard::flex_dashboard:
    theme: simplex

---

```{r setup, include = FALSE}
library(tidyverse)
library(flexdashboard)
library(plotly)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))
          
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


```{r load_data}
ny_local = 
  read_csv("./data/ny_local.csv")

covid_symptom_df =
  read_csv("./data/Anxiety_Depression.csv") %>% 
  janitor::clean_names() %>% 
  filter(state == "New York") %>% 
  mutate(
    indicator_id = case_when(
      indicator == "Symptoms of Anxiety Disorder" ~ "Anxiety",
      indicator == "Symptoms of Anxiety Disorder or Depressive Disorder" ~ "Anxiety/Depressive",
      indicator == "Symptoms of Depressive Disorder" ~ "Depressive"
  ))

mental_care_df =
  read_csv("./data/Mental_Health_Care.csv") %>% 
  janitor::clean_names() %>% 
  filter(state == "New York") %>% 
  mutate(
    indicator_id = case_when(
      indicator == "Needed Counseling or Therapy But Did Not Get It, Last 4 Weeks" ~ "No Therapy",
      indicator == "Received Counseling or Therapy, Last 4 Weeks" ~ "Therapy",
      indicator == "Took Prescription Medication for Mental Health And/Or Received Counseling or Therapy, Last 4 Weeks" ~ "Med/Therapy",
      indicator == "Took Prescription Medication for Mental Health, Last 4 Weeks" ~ "Med"
    )
  )
```

```{r}
write_csv(ny_local, "./data/ny_local.csv")
```


Page 1
=====================================  

Column
-------------------------------------
    
### Chart 1
    
```{r}
ub_overall_plot =
  ny_local %>% 
  select(category, measure_id, data_value) %>% 
  filter(category == "Unhealthy Behaviors") %>% 
  ggplot(aes(x = measure_id, y = data_value, color = measure_id)) +
  geom_boxplot() +
  labs(
    x = "Unhealthy Behavior",
    y = "Prevalence (%)"
  ) +
  scale_y_continuous(limits = c(0, 100)) +
  theme(legend.position = "none") +
  scale_x_discrete(labels = c("Binge Drinking", "Current Smoking", "Physical Inactivity", "Obesity", "Sleep < 7 hrs"))

ggplotly(ub_overall_plot)
```
   
Column {.tabset}
-------------------------------------
   
### Chart 2


```{r}
mental_health_value =
  ny_local %>%
  select(unique_id, data_value, measure_id, population_count) %>% 
  filter(measure_id == "MHLTH") %>% 
  mutate(value_mental = data_value) %>% 
  select(unique_id, value_mental, population_count)

current_smoking_value =
  ny_local %>%
  select(unique_id, data_value, measure_id, population_count) %>% 
  filter(measure_id == "CSMOKING") %>% 
  mutate(value_smoking = data_value) %>% 
  select(unique_id, value_smoking, population_count)

mental_smoking =
  left_join(mental_health_value, current_smoking_value) %>% 
  drop_na()


current_smoking_plot =
  mental_smoking %>% 
  ggplot(aes(x = value_mental, y = value_smoking, size = population_count)) +
  geom_point(alpha = 0.5, color = "steel blue") +
  labs(
    x = "Mental Health Prevalence (%)",
    y = "Unhealthy Behavior Prevalence (%)",
    title = "Current Smoking"
  ) +
  scale_y_continuous(limits = c(0, 100)) 

ggplotly(current_smoking_plot)
```   

### Chart 3
    
```{r}
binge_drinking_value =
  ny_local %>% 
  select(unique_id, data_value, measure_id) %>% 
  filter(measure_id == "BINGE") %>% 
  mutate(value_binge_drinking = data_value) %>% 
  select(unique_id, value_binge_drinking)

binge_drinking =
  left_join(mental_health_value, binge_drinking_value)

binge_drinking_plot =
  binge_drinking %>% 
  ggplot(aes(x = value_mental, y = value_binge_drinking, size = population_count)) +
  geom_point(alpha = 0.5, color = "darkorchid4") +
  labs(
    x = "Mental Health Prevalence (%)",
    y = "Unhealthy Behavior Prevalence (%)",
    title = "Binge Drinking"
  ) +
  scale_y_continuous(limits = c(0, 100))

ggplotly(binge_drinking_plot)
```

### Chart 4
    
```{r}
physical_inactivity_value =
  ny_local %>% 
  select(unique_id, data_value, measure_id) %>% 
  filter(measure_id == "LPA") %>% 
  mutate(value_physical_inactive = data_value) %>% 
  select(unique_id, value_physical_inactive)

physical_inactivity =
  left_join(mental_health_value, physical_inactivity_value)

physical_inactivity_plot =
  physical_inactivity %>% 
  ggplot(aes(x = value_mental, y = value_physical_inactive, size = population_count)) +
  geom_point(alpha = 0.5, color = "darkcyan") +
  labs(
    x = "Mental Health Prevalence (%)",
    y = "Unhealthy Behavior Prevalence (%)",
    title = "Physical Inactivity"
  ) +
  scale_y_continuous(limits = c(0, 100))

ggplotly(physical_inactivity_plot)
```

### Chart 5
    
```{r}
obesity_value =
  ny_local %>% 
  select(unique_id, data_value, measure_id) %>% 
  filter(measure_id == "OBESITY") %>% 
  mutate(value_obesity = data_value) %>% 
  select(unique_id, value_obesity)

obesity =
  left_join(mental_health_value, obesity_value)

obesity_plot =
  obesity %>% 
  ggplot(aes(x = value_mental, y = value_obesity, size = population_count)) +
  geom_point(alpha = 0.5, color = "chartreuse4") +
  labs(
    x = "Mental Health Prevalence (%)",
    y = "Unhealthy Behavior Prevalence (%)",
    title = "Obesity"
  ) +
  scale_y_continuous(limits = c(0, 100))

ggplotly(obesity_plot)
```

### Chart 6
    
```{r}
sleep_value =
  ny_local %>% 
  select(unique_id, data_value, measure_id) %>% 
  filter(measure_id == "SLEEP") %>% 
  mutate(value_sleep = data_value) %>% 
  select(unique_id, value_sleep)

sleep =
  left_join(mental_health_value, sleep_value)

sleep_plot =
  sleep %>% 
  ggplot(aes(x = value_mental, y = value_sleep, size = population_count)) +
  geom_point(alpha = 0.5, color = "darkgoldenrod2") +
  labs(
    x = "Mental Health Prevalence (%)",
    y = "Unhealthy Behavior Prevalence (%)",
    title = "Sleep < 7 hours"
  ) +
  scale_y_continuous(limits = c(0, 100))

ggplotly(sleep_plot)
```


Page 2 {data-orientation=columns}
=====================================     
   
Column
-------------------------------------

### Chart 1

```{r}
prevention_plot = 
  ny_local %>% 
  filter(category == "Prevention") %>% 
  select(measure_id, data_value) %>% 
  group_by(measure_id) %>% 
  ggplot(aes(x = measure_id, y = data_value, color = measure_id)) +
  geom_boxplot() +
  labs(
       x = "Prevention", 
       y = "Prevalence (%)") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1), legend.position = "none")  +
  scale_y_continuous(limits = c(0, 100)) +
  scale_x_discrete(labels = c("Health Insurance", "BP Med", "Annual Checkup", "Cholesterol Screening", "Colon Screening", "Core preventive services for men", "Core preventive services for women", "Dental Visit", "Mammography", "Pap Smear Test"))

ggplotly(prevention_plot)
```

Column {.tabset}
-------------------------------------
   
### Chart 2

```{r}
mental_health_df = 
  ny_local %>% 
  select(unique_id, data_value, measure_id, population_count) %>% 
  filter(measure_id == "MHLTH") %>% 
  mutate(value_mental = data_value) %>% 
  select(unique_id, value_mental, population_count)


checkup_df =
  ny_local %>% 
  select(unique_id, data_value, measure_id) %>% 
  filter(measure_id == "CHECKUP") %>% 
  mutate(value_checkup = data_value) %>% 
  select(unique_id, value_checkup)


mental_checkup = 
  left_join(mental_health_df, checkup_df)

mental_checkup_plot = 
  mental_checkup %>% 
  ggplot(aes(x = value_mental, y = value_checkup, size = population_count)) +
  geom_point(alpha = 0.5, color = "steel blue") +
  labs(title = "Current Annual Checkup",
       x = 'Mental Health Prevalence (%)', 
       y = 'Prevention Prevalence (%)') +
  scale_y_continuous(limits = c(0, 100))

ggplotly(mental_checkup_plot)
```   
    
### Chart 3

```{r}
insurance_df =
  ny_local %>% 
  select(unique_id, data_value, measure_id, population_count) %>% 
  filter(measure_id == "ACCESS2") %>% 
  mutate(value_insurance = data_value) %>% 
  select(unique_id, value_insurance, population_count)

mental_insurance = 
  left_join(mental_health_df, insurance_df)

mental_insurance_plot = 
  mental_insurance %>%
  ggplot(aes(x = value_mental, y = value_insurance, size = population_count)) +
  geom_point(alpha = 0.5, color = "chartreuse4") +
  labs(title = "Current Lack of Insurance",
       x = "Mental Health Prevalence (%)", 
       y = "Prevention Prevalence (%)") +
  scale_y_continuous(limits = c(0, 100))

ggplotly(mental_insurance_plot)
```

### Chart 4

```{r}
bp_med_df =
  ny_local %>% 
  select(unique_id, data_value, measure_id, population_count) %>% 
  filter(measure_id == "BPMED") %>% 
  mutate(value_bp_med = data_value) %>% 
  select(unique_id, value_bp_med, population_count)

mental_bp_med = 
  left_join(mental_health_df, bp_med_df)

mental_bp_med_plot = 
  mental_bp_med %>%
  ggplot(aes(x = value_mental, y = value_bp_med, size = population_count)) +
  geom_point(alpha = 0.5, color = "#CCCC00") +
  labs(title = "Taking BP Medication",
       x = "Mental Health Prevalence (%)", 
       y = "Prevention Prevalence (%)") +
  scale_y_continuous(limits = c(0, 100))

ggplotly(mental_bp_med_plot)
```

### Chart 5

```{r}
cholest_df =
  ny_local %>% 
  select(unique_id, data_value, measure_id, population_count) %>% 
  filter(measure_id == "CHOLSCREEN") %>% 
  mutate(value_cholest = data_value) %>% 
  select(unique_id, value_cholest, population_count)

mental_cholest = 
  left_join(mental_health_df, cholest_df)

mental_cholest_plot = 
  mental_cholest %>%
  ggplot(aes(x = value_mental, y = value_cholest, size = population_count)) +
  geom_point(alpha = 0.5, color = "#FF6666") +
  labs(title = "Cholesterol Screening",
       x = "Mental Health Prevalence (%)", 
       y = "Prevention Prevalence (%)") +
  scale_y_continuous(limits = c(0, 100))

ggplotly(mental_cholest_plot)
```

### Chart 6

```{r}
colon_df =
  ny_local %>% 
  select(unique_id, data_value, measure_id, population_count) %>% 
  filter(measure_id == "COLON_SCREEN") %>% 
  mutate(value_colon = data_value) %>% 
  select(unique_id, value_colon, population_count)

mental_colon = 
  left_join(mental_health_df, colon_df)

mental_colon_plot = 
  mental_colon %>%
  ggplot(aes(x = value_mental, y = value_colon, size = population_count)) +
  geom_point(alpha = 0.5, color = "#993399") +
  labs(title = "Colorectal Cancer Screening",
       x = "Mental Health Prevalence (%)", 
       y = "Prevention Prevalence (%)") +
  scale_y_continuous(limits = c(0, 100))

ggplotly(mental_colon_plot)
```

### Chart 7

```{r}
dental_df =
  ny_local %>% 
  select(unique_id, data_value, measure_id, population_count) %>% 
  filter(measure_id == "DENTAL") %>% 
  mutate(value_dental = data_value) %>% 
  select(unique_id, value_dental, population_count)

mental_dental = 
  left_join(mental_health_df, dental_df)

mental_dental_plot = 
  mental_dental %>%
  ggplot(aes(x = value_mental, y = value_dental, size = population_count)) +
  geom_point(alpha = 0.5, color = "#66CCFF") +
  labs(title = "Dental Visit",
       x = "Mental Health Prevalence (%)", 
       y = "Prevention Prevalence (%)") +
  scale_y_continuous(limits = c(0, 100))

ggplotly(mental_dental_plot)
```

### Chart 8

```{r}
mammography_df =
  ny_local %>% 
  select(unique_id, data_value, measure_id, population_count) %>% 
  filter(measure_id == "MAMMOUSE") %>% 
  mutate(value_mammography = data_value) %>% 
  select(unique_id, value_mammography, population_count)

mental_mammography = 
  left_join(mental_health_df, mammography_df)

mental_mammography_plot = 
  mental_mammography %>%
  ggplot(aes(x = value_mental, y = value_mammography, size = population_count)) +
  geom_point(alpha = 0.5, color = "#00CC66") +
  labs(title = "Mammography",
       x = "Mental Health Prevalence (%)", 
       y = "Prevention Prevalence (%)") +
  scale_y_continuous(limits = c(0, 100))

ggplotly(mental_mammography_plot)
```

### Chart 9

```{r}
pap_smear_df =
  ny_local %>% 
  select(unique_id, data_value, measure_id, population_count) %>% 
  filter(measure_id == "PAPTEST") %>% 
  mutate(value_pap_smear = data_value) %>% 
  select(unique_id, value_pap_smear, population_count)

mental_pap_smear = 
  left_join(mental_health_df, pap_smear_df)

mental_pap_smear_plot = 
  mental_pap_smear %>%
  ggplot(aes(x = value_mental, y = value_pap_smear, size = population_count)) +
  geom_point(alpha = 0.5, color = "#CC9900") +
  labs(title = "Pap Smear Test",
       x = "Mental Health Prevalence (%)", 
       y = "Prevention Prevalence (%)") +
  scale_y_continuous(limits = c(0, 100))

ggplotly(mental_pap_smear_plot)
```

### Chart 10

```{r}
cpmen_df =
  ny_local %>% 
  select(unique_id, data_value, measure_id, population_count) %>% 
  filter(measure_id == "COREM") %>% 
  mutate(value_cpmen = data_value) %>% 
  select(unique_id, value_cpmen, population_count)

mental_cpmen = 
  left_join(mental_health_df, cpmen_df)

mental_cpmen_plot = 
  mental_cpmen %>%
  ggplot(aes(x = value_mental, y = value_cpmen, size = population_count)) +
  geom_point(alpha = 0.5, color = "#FFCC33") +
  labs(title = "Core Preventive Services for Men",
       x = "Mental Health Prevalence (%)", 
       y = "Prevention Prevalence (%)") +
  scale_y_continuous(limits = c(0, 100))

ggplotly(mental_cpmen_plot)
```

### Chart 11

```{r}
cpwomen_df =
  ny_local %>% 
  select(unique_id, data_value, measure_id, population_count) %>% 
  filter(measure_id == "COREW") %>% 
  mutate(value_cpwomen = data_value) %>% 
  select(unique_id, value_cpwomen, population_count)

mental_cpwomen = 
  left_join(mental_health_df, cpwomen_df)

mental_cpwomen_plot = 
  mental_cpwomen %>%
  ggplot(aes(x = value_mental, y = value_cpwomen, size = population_count)) +
  geom_point(alpha = 0.5, color = "#FF9966") +
  labs(title = "Core Preventive Services for Women",
       x = "Mental Health Prevalence (%)", 
       y = "Prevention Prevalence (%)") +
  scale_y_continuous(limits = c(0, 100))

ggplotly(mental_cpwomen_plot)
```


Page 3 {data-orientation=columns}
=====================================  

Column
-------------------------------------

### Chart 1


```{r}
treatment_plot =
  mental_care_df %>% 
  ggplot(aes(x = indicator_id, y = value, color = indicator_id)) +
  geom_boxplot() +
  labs(
    x = "Treatment",
    y = "Percentage"
  ) +
  theme(legend.position = "none")

ggplotly(treatment_plot)
```

Column {.tabset}
-------------------------------------

### Chart 2

```{r}
anxiety_depression_plot =  
  covid_symptom_df %>%
  ggplot(aes(x = time_period, y = value, color = indicator_id)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    limits = c(1, 18),
    breaks = seq(1, 18, 1)
  ) +
  labs(
    x = "Time (week)",
    y = "Percentage"
  ) +
  theme(legend.position = "none")

ggplotly(anxiety_depression_plot)
```

### Chart 3
  
```{r}
mental_care_plot =
  mental_care_df %>% 
  ggplot(aes(x = time_period, y = value, color = indicator_id)) +
  geom_point() +
  geom_line() +
  labs(
    x = "Time (week)",
    y = "Percentage"
  ) +
  theme(legend.position = "none")

ggplotly(mental_care_plot)
```


