---
title: "Interactive Map"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
  runtime: shiny
---



```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(httr)
library(shiny)
library(leaflet)
library(stringr)
library(dplyr)
library(rsconnect)
```


```{r, include = FALSE}
# import the 500 cities local healt data
ny_local = 
  read_csv("./data/500_Cities.csv") %>% 
  janitor::clean_names() %>% 
  filter(state_abbr == "NY")
```



```{r, include = FALSE}
# clean the dataset 
coordinate_df =
  ny_local %>% 
  select(year, category, unique_id, city_name, measure, category_id, measure_id, data_value, geo_location, 
         short_question_text, population_count) %>% 
  mutate(
    geo_location = str_replace_all(string = geo_location, pattern = "[\\*\\(\\)]", replace = "")) %>% 
  separate(geo_location, into = c("lat", "long"), ",", convert = TRUE)
```

Column {.sidebar}
-----------------------------------------------------------------------
```{r}
category_levels = coordinate_df %>% pull(category) %>% unique()
citynames = coordinate_df %>% distinct(city_name) %>% pull()


radioButtons(
  "health_concern_category", 
  label = h3("Health-Related Concern Category"),
  choices = category_levels, selected = "Unhealthy Behaviors")


selectInput(
  "city_choice",
  h3("City of Interest"),
  choices = citynames,
  selected = "New York"
)


sliderInput(
  "prevalence_of_measure",
  h3("Prevalence in %"),
  0, 100,
  value = c(10,70)
)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
pal = colorNumeric(
  palette = "viridis",
  domain = coordinate_df$data_value
)

renderLeaflet({
  coordinate_df %>% 
    filter(
      category == input[["health_concern_category"]],
      data_value %in% input[["prevalence_of_measure"]][1]:input[["prevalence_of_measure"]][2],
      city_name== input[["city_choice"]]) %>%
    leaflet() %>% 
    addProviderTiles(providers$CartoDB.Positron) %>% 
    addCircleMarkers(data = coordinate_df, lat = ~lat, lng = ~long, radius = .1, color = ~pal(data_value))
})
```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B


```{r}
renderPlotly({
  coordinate_df %>% 
  filter(
      category == input[["health_concern_category"]],
      data_value %in% input[["prevalence_of_measure"]][1]:input[["prevalence_of_measure"]][2],
      city_name== input[["city_choice"]]) %>%
  group_by(short_question_text) %>% 
  plot_ly(
  x = ~short_question_text, y = ~population_count, color = ~short_question_text,
  type = "bar", colors = "viridis")
})
```