---
title: "Inpatient Cost in NY Report"
author: Danyang Gui, Jingyi Zhang, Zihan Yu, Kexin Sun, Yining Xiang
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
```

<br />

## Motivation

Mental health disorders, including clinical depression, manic depression, schizophrenia, and obsessive-compulsive disorder, account for several of the top causes of disability in the United States and worldwide. An estimated 26% of Americans ages 18 and older -- about 1 in 4 adults -- suffers from a diagnosable mental disorder in a given year. As residents-to-be, we are collectively interested in investigating the risk factors that contribute to mental health disorders in New York State and hopefully providing some insightful analysis on mental health related concerns in this COVID-19 era. *[Cited from JHU Medicine](https://www.hopkinsmedicine.org/health/wellness-and-prevention/mental-health-disorder-statistics#:~:text=An%20estimated%2026%25%20of%20Americans,substance%20abuse%20and%20anxiety%20disorders.)

Facts

Goals of our project

<br />

## Related Work

<br />

## Initial questions

<br />

## Data

<br />

## Exploratoy Analysis

<br />

## Findings

<br />

## Additional analysis

<br />

## Discussion








